[tool.ruff]
line-length = 80
target-version = "py311"

[tool.ruff.lint]
select = ["B", "E", "F", "I", "N", "PLC", "PLE", "SIM", "W"]
ignore = ["B024"]

[tool.ruff.lint.isort]
force-single-line = true
force-sort-within-sections = true
single-line-exclusions = ["collections.abc", "typing"]
